#  _    _ _     _                    _____ _    _ _____
# | |  | (_)   | |                  / ____| |  | |_   _|
# | |__| |_ ___| |_ ___  _ __ _   _| |  __| |  | | | |
# |  __  | / __| __/ _ \| '__| | | | | |_ | |  | | | |
# | |  | | \__ \ || (_) | |  | |_| | |__| | |__| |_| |_
# |_|  |_|_|___/\__\___/|_|   \__, |\_____|\____/|_____|
#                              __/ |
#                             |___/
#
# History Gui - config.yml - Plugin Configuration
# Copyright 2020 Zach_FR | All Rights Reserved
#  Helpful Links:
#   Support |   https://discord.zachfr.com
#   Docs    |   https://docs.zachfr.com

# Should we allow edit punishment on gui?
Allow edit punishment: true

# Should we only show offline players in browser gui?
Offline player: true

# Allow browser gui
Allow browser gui: true

# Should we load player head skin in browser gui (May cause some lag if you enable)?
Player head:
  Enable: true
  # Item if disable
  Item: PLAYER_HEAD